---
- name: Check if CSF is installed
  stat:
    path: /usr/sbin/csf
  register: csf_check
  changed_when: false
  check_mode: no
  tags: always

- name: Create csf_installed variable.
  set_fact:
    csf_installed: "{{ csf_check.stat.exists|bool }}"
  check_mode: no
  tags: always

#- name: Include CSF dependencies Task
#  include: dependencies.yml
#  when: csf_installed != true and (install_csf is defined and install_csf == true)

- name: Disable firewall
  include: disable_firewall.yml
  when: csf_installed != true and (install_csf is defined and install_csf == true)

- name: Include CSF Installer Task
  include: install.yml
  when: csf_installed != true and (install_csf is defined and install_csf == true)
