---
install_csf: true

csf_testing: 0
csf_restrict_syslog: "3"
csf_tcp_in: 20,21,22,25,53,80,110,143,443,465,587,993,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,2222,3306,5666,30000:35000
csf_tcp_out: 20,21,22,25,37,43,53,80,110,113,443,587,873,993,995,2086,2087,2089,2703,5665
csf_udp_in: 20,21,53
csf_udp_out: 20,21,53,113,123,873,6277,24441

csf_eth_device: "{{ ansible_default_ipv4.interface }}"
csf_eth6_device: "{% if ansible_default_ipv6.interface is defined %} {{ ansible_default_ipv6.interface }} {% endif %}"

csf_syslog_check: 1800
csf_pt_deleted: 1
csf_pt_all_users: 1
csf_lf_script_limit: 250

# DOS PROTECTION
csf_connlimit: 22;tcp;20;250,80;tcp;50;250,443;tcp;50;250,21;tcp;20;250 # port1;protocol1;connection_count1;time1,port2;protocol2;connection_count2;time2
csf_portflood: 22;tcp;20;5,80;tcp;20;5,443;tcp;20;5,21;tcp;20;5
csf_ct_limit: 100
csf_ct_interval: 20
csf_ct_ports: 80,443

csf_lf_alert_to: "{{ csf_email_to }}"
csf_lf_alert_from: "csf@{{ ansible_hostname }}"
csf_smtp_block: 1
csf_lf_email_alert: 1
csf_lf_script_alert: 1

### Messenger ### (NOT ENABLED NOW)
csf_messenger: 0
csf_messenger_html: 8888
csf_messenger_html_in: "80,443,2082,2083,2086,2087,2095,2096"
csf_messenger_text: 8889
csf_messenger_text_in: 21
